### ISSUE TITLE
follow instruction "bundle exec rake db:create" give an error

### ISSUE THREAD

**Issue by linediconsine** [linediconsine/tabae#1]
`bundle exec rake db:create`

I see this error:
```
rake aborted!
ActiveRecord::AdapterNotSpecified: The `development` database is not configured for the `development` environment.

Available databases configurations are:

default
/Users/linediconsine/Desktop/test2/tabae/app/models/application_record.rb:1:in `<main>'
/Users/linediconsine/Desktop/test2/tabae/app/models/user.rb:1:in `<main>'
/Users/linediconsine/Desktop/test2/tabae/config/routes.rb:3:in `block in <main>'
/Users/linediconsine/Desktop/test2/tabae/config/routes.rb:1:in `<main>'
/Users/linediconsine/Desktop/test2/tabae/config/environment.rb:5:in `<main>'
/Users/linediconsine/.rbenv/versions/2.7.1/bin/bundle:23:in `load'
/Users/linediconsine/.rbenv/versions/2.7.1/bin/bundle:23:in `<main>'
Tasks: TOP => db:create => db:load_config => environment
(See full trace by running task with --trace)
```

I am on Osx Big Sur

**Comment by linediconsine** [comment]
Seem fixed on branch main
